### ISSUE TITLE
can't create directory '/opt/imapfilter/': Permission denied

### ISSUE THREAD

**Issue by sanderdewitte** [ntnn/docker-imapfilter#33]
Since commit entitled "feat: non-root user" on Feb 5, 2023, I have been getting errors starting your imapfilter Docker container (from https://hub.docker.com/r/ntnn/imapfilter, tag: "latest-tag"). It keeps restarting with the following error in the logs coming from the `entrypoint.sh` script:
```
>>> Config has not been cloned yet, cloning
mkdir: can't create directory '/opt/imapfilter/': Permission denied
```
Since adding and using the imapfilter user (uid:1001) in the Dockerfile, the `entrypoint.sh` script cannot create the directory defined in  `$config_target_prefix`. The imapfilter user does not have the correct privileges to write in `/opt`.

**Comment by ntnn** [comment]
Thanks, I merged #34 which should fix the issue. Please test.

**Comment by sanderdewitte** [comment]
Tested successfully with latest imapfilter Docker container, tag: "latest-tag". Thanks.

**Comment by ntnn** [comment]
Awesome, thank!
